# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Jirka Vejrazka <Jirka.Vejrazka@gmail.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version: Django REST framework\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-01-30 16:23+0000\n"
"PO-Revision-Date: 2015-01-30 16:27+0000\n"
"Last-Translator: Thomas Christie <tom@tomchristie.com>\n"
"Language-Team: Czech (http://www.transifex.com/projects/p/django-rest-framework/language/cs/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: cs\n"
"Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;\n"

#: authentication.py:69
msgid "Invalid basic header. No credentials provided."
msgstr "Chybná hlavička. Nebyly poskytnuty přihlašovací údaje."

#: authentication.py:72
msgid "Invalid basic header. Credentials string should not contain spaces."
msgstr "Chybná hlavička. Přihlašovací údaje by neměly obsahovat mezery."

#: authentication.py:78
msgid "Invalid basic header. Credentials not correctly base64 encoded."
msgstr "Chybná hlavička. Přihlašovací údaje nebyly správně zakódovány pomocí base64."

#: authentication.py:90
msgid "Invalid username/password."
msgstr "Chybné uživatelské jméno nebo heslo."

#: authentication.py:156
msgid "Invalid token header. No credentials provided."
msgstr "Chybná hlavička tokenu. Nebyly zadány přihlašovací údaje."

#: authentication.py:159
msgid "Invalid token header. Token string should not contain spaces."
msgstr "Chybná hlavička tokenu. Přihlašovací údaje by neměly obsahovat mezery."

#: authentication.py:168
msgid "Invalid token."
msgstr "Chybný token."

#: authentication.py:171
msgid "User inactive or deleted."
msgstr "Uživatelský účet je neaktivní nebo byl smazán."

#: exceptions.py:38
msgid "A server error occurred."
msgstr "Chyba na straně serveru."

#: exceptions.py:73
msgid "Malformed request."
msgstr "Neplatný formát požadavku."

#: exceptions.py:78
msgid "Incorrect authentication credentials."
msgstr "Chybné přihlašovací údaje."

#: exceptions.py:83
msgid "Authentication credentials were not provided."
msgstr "Přihlašovací údaje nebyly zadány."

#: exceptions.py:88
msgid "You do not have permission to perform this action."
msgstr "K této akci nemáte oprávnění."

#: exceptions.py:93
msgid "Not found."
msgstr "Nenalezeno."

#: exceptions.py:98
msgid "Method \"{method}\" not allowed."
msgstr "Metoda \"{method}\" není povolena."

#: exceptions.py:109
msgid "Could not satisfy the request Accept header."
msgstr "Nelze vyhovět požadavku v hlavičce Accept."

#: exceptions.py:121
msgid "Unsupported media type \"{media_type}\" in request."
msgstr "Nepodporovaný media type \"{media_type}\" v požadavku."

#: exceptions.py:134
msgid "Request was throttled."
msgstr "Pořadavek byl limitován kvůli omezení počtu požadavků za časovou periodu."

#: fields.py:153 relations.py:132 relations.py:156 validators.py:77
#: validators.py:155
msgid "This field is required."
msgstr "Toto pole je vyžadováno."

#: fields.py:154
msgid "This field may not be null."
msgstr "Toto pole nesmí být prázdné (null)."

#: fields.py:487 fields.py:515
msgid "\"{input}\" is not a valid boolean."
msgstr "\"{input}\" nelze použít jako typ boolean."

#: fields.py:550
msgid "This field may not be blank."
msgstr "Toto pole nesmí být prázdné.."

#: fields.py:551 fields.py:1324
msgid "Ensure this field has no more than {max_length} characters."
msgstr "Zkontrolujte, že toto pole není delší než {max_length} znaků."

#: fields.py:552
msgid "Ensure this field has at least {min_length} characters."
msgstr "Zkontrolujte, že toto obsahuje alespoň {min_length} znaků"

#: fields.py:587
msgid "Enter a valid email address."
msgstr "Vložte platnou e-mailovou adresu."

#: fields.py:604
msgid "This value does not match the required pattern."
msgstr "Hodnota v tomto poli neodpovídá požadovanému formátu."

#: fields.py:615
msgid ""
"Enter a valid \"slug\" consisting of letters, numbers, underscores or "
"hyphens."
msgstr "Vložte platnou \"zkrácenou formu\" obsahující pouze malá písmena, čísla, spojovník nebo podtržítko."

#: fields.py:627
msgid "Enter a valid URL."
msgstr "Vložte platný odkaz."

#: fields.py:638
msgid "\"{value}\" is not a valid UUID."
msgstr ""

#: fields.py:657
msgid "A valid integer is required."
msgstr "Je vyžadováno číslo."

#: fields.py:658 fields.py:692 fields.py:725
msgid "Ensure this value is less than or equal to {max_value}."
msgstr "Zkontrolujte, že hodnota je menší nebo rovna {max_value}."

#: fields.py:659 fields.py:693 fields.py:726
msgid "Ensure this value is greater than or equal to {min_value}."
msgstr "Zkontrolujte, že hodnota je větší nebo rovna {min_value}."

#: fields.py:660 fields.py:694 fields.py:730
msgid "String value too large."
msgstr "Řetězec je příliš dlouhý"

#: fields.py:691 fields.py:724
msgid "A valid number is required."
msgstr "Je vyžadováno číslo."

#: fields.py:727
msgid "Ensure that there are no more than {max_digits} digits in total."
msgstr "Zkontrolujte, že číslo neobsahuje více než {max_digits} čislic."

#: fields.py:728
msgid ""
"Ensure that there are no more than {max_decimal_places} decimal places."
msgstr "Zkontrolujte, že číslo nemá více než {max_decimal_places} desetinných míst."

#: fields.py:729
msgid ""
"Ensure that there are no more than {max_whole_digits} digits before the "
"decimal point."
msgstr "Zkontrolujte, že číslo neobsahuje více než {max_whole_digits} čislic před desetinnou čárkou."

#: fields.py:813
msgid "Datetime has wrong format. Use one of these formats instead: {format}."
msgstr "Chybný formát data a času. Použijte jeden z těchto formátů: {format}."

#: fields.py:814
msgid "Expected a datetime but got a date."
msgstr "Bylo zadáno pouze datum místo data a času."

#: fields.py:878
msgid "Date has wrong format. Use one of these formats instead: {format}."
msgstr "Chybný formát data. Použijte jeden z těchto formátů: {format}."

#: fields.py:879
msgid "Expected a date but got a datetime."
msgstr "Bylo zadáno datum a čas, místo samotného data."

#: fields.py:936
msgid "Time has wrong format. Use one of these formats instead: {format}."
msgstr "Chybný formát času. Použijte jeden z těchto formátů: {format}."

#: fields.py:992 fields.py:1036
msgid "\"{input}\" is not a valid choice."
msgstr "\"{input}\" není platnou možností."

#: fields.py:1037 fields.py:1151 serializers.py:482
msgid "Expected a list of items but got type \"{input_type}\"."
msgstr "Byl očekáván seznam položek ale nalezen \"{input_type}\"."

#: fields.py:1067
msgid "No file was submitted."
msgstr "Nebyl zaslán žádný soubor."

#: fields.py:1068
msgid ""
"The submitted data was not a file. Check the encoding type on the form."
msgstr "Zaslaná data neobsahují soubor. Zkontrolujte typ kódování ve formuláři."

#: fields.py:1069
msgid "No filename could be determined."
msgstr "Nebylo možno zjistit jméno souboru."

#: fields.py:1070
msgid "The submitted file is empty."
msgstr "Zaslaný soubor je prázdný."

#: fields.py:1071
msgid ""
"Ensure this filename has at most {max_length} characters (it has {length})."
msgstr "Zajistěte, aby jméno souboru obsahovalo maximálně {max_length} znaků (teď má {length} znaků)."

#: fields.py:1113
msgid ""
"Upload a valid image. The file you uploaded was either not an image or a "
"corrupted image."
msgstr "Nahrajte platný obrázek. Nahraný soubor buď není obrázkem, nebo je poškozen."

#: fields.py:1188
msgid "Expected a dictionary of items but got type \"{input_type}\"."
msgstr ""

#: pagination.py:221
msgid "Invalid page \"{page_number}\": {message}."
msgstr "Chybné čislo stránky \"{page_number}\": {message}."

#: pagination.py:442
msgid "Invalid cursor"
msgstr ""

#: relations.py:133
msgid "Invalid pk \"{pk_value}\" - object does not exist."
msgstr "Chybný primární klíč \"{pk_value}\" - objekt neexistuje."

#: relations.py:134
msgid "Incorrect type. Expected pk value, received {data_type}."
msgstr "Chybný typ. Byl přijat typ {data_type} místo hodnoty primárního klíče."

#: relations.py:157
msgid "Invalid hyperlink - No URL match."
msgstr "Chybný odkaz - nebyla nalezena žádní shoda."

#: relations.py:158
msgid "Invalid hyperlink - Incorrect URL match."
msgstr "Chybný odkaz - byla nalezena neplatná shoda."

#: relations.py:159
msgid "Invalid hyperlink - Object does not exist."
msgstr "Chybný odkaz - objekt neexistuje."

#: relations.py:160
msgid "Incorrect type. Expected URL string, received {data_type}."
msgstr "Chybný typ. Byl přijat typ {data_type} místo očekávaného odkazu."

#: relations.py:295
msgid "Object with {slug_name}={value} does not exist."
msgstr "Objekt s {slug_name}={value} neexistuje."

#: relations.py:296
msgid "Invalid value."
msgstr "Chybná hodnota."

#: serializers.py:299
msgid "Invalid data. Expected a dictionary, but got {datatype}."
msgstr "Chybná data. Byl přijat typ {datatype} místo očakávaného slovníku."

#: validators.py:22
msgid "This field must be unique."
msgstr "Tato položka musí být unikátní."

#: validators.py:76
msgid "The fields {field_names} must make a unique set."
msgstr "Položka {field_names} musí tvořit unikátní množinu."

#: validators.py:219
msgid "This field must be unique for the \"{date_field}\" date."
msgstr "Tato položka musí být pro datum \"{date_field}\" unikátní."

#: validators.py:234
msgid "This field must be unique for the \"{date_field}\" month."
msgstr "Tato položka musí být pro měsíc \"{date_field}\" unikátní."

#: validators.py:247
msgid "This field must be unique for the \"{date_field}\" year."
msgstr "Tato položka musí být pro rok \"{date_field}\" unikátní."

#: versioning.py:39
msgid "Invalid version in \"Accept\" header."
msgstr "Chybné číslo verze v hlavičce Accept"

#: versioning.py:70 versioning.py:112
msgid "Invalid version in URL path."
msgstr "Chybné číslo verze v odkazu."

#: versioning.py:138
msgid "Invalid version in hostname."
msgstr "Chybné číslo verze v hostname."

#: versioning.py:160
msgid "Invalid version in query parameter."
msgstr "Chybné čislo verze v URL parametru."

#: authtoken/serializers.py:20
msgid "User account is disabled."
msgstr "Uživatelský účet je zamčen."

#: authtoken/serializers.py:23
msgid "Unable to log in with provided credentials."
msgstr "Se zadanými údaji nebylo možné se přihlásit."

#: authtoken/serializers.py:26
msgid "Must include \"username\" and \"password\"."
msgstr "Musí obsahovat \"uživatelské jméno! a \"heslo\"."
