# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Tõnis Kärdi <tonis.kardi@gmail.com>, 2015
msgid ""
msgstr ""
"Project-Id-Version: Django REST framework\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-01-30 16:23+0000\n"
"PO-Revision-Date: 2015-02-27 16:24+0000\n"
"Last-Translator: Tõnis Kärdi <tonis.kardi@gmail.com>\n"
"Language-Team: Estonian (http://www.transifex.com/projects/p/django-rest-framework/language/et/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: et\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: authentication.py:69
msgid "Invalid basic header. No credentials provided."
msgstr "Sobimatu lihtpäis. Kasutajatunnus on esitamata."

#: authentication.py:72
msgid "Invalid basic header. Credentials string should not contain spaces."
msgstr "Sobimatu lihtpäis. Kasutajatunnus ei tohi sisaldada tühikuid."

#: authentication.py:78
msgid "Invalid basic header. Credentials not correctly base64 encoded."
msgstr "Sobimatu lihtpäis. Kasutajatunnus pole korrektselt base64-kodeeritud."

#: authentication.py:90
msgid "Invalid username/password."
msgstr "Sobimatu kasutajatunnus/salasõna."

#: authentication.py:156
msgid "Invalid token header. No credentials provided."
msgstr "Sobimatu lubakaardi päis. Kasutajatunnus on esitamata."

#: authentication.py:159
msgid "Invalid token header. Token string should not contain spaces."
msgstr "Sobimatu lubakaardi päis. Loa sõne ei tohi sisaldada tühikuid."

#: authentication.py:168
msgid "Invalid token."
msgstr "Sobimatu lubakaart."

#: authentication.py:171
msgid "User inactive or deleted."
msgstr "Kasutaja on inaktiivne või kustutatud."

#: exceptions.py:38
msgid "A server error occurred."
msgstr "Viga serveril."

#: exceptions.py:73
msgid "Malformed request."
msgstr "Väändunud päring."

#: exceptions.py:78
msgid "Incorrect authentication credentials."
msgstr "Ebakorrektne autentimistunnus."

#: exceptions.py:83
msgid "Authentication credentials were not provided."
msgstr "Autentimistunnus on esitamata."

#: exceptions.py:88
msgid "You do not have permission to perform this action."
msgstr "Teil puuduvad piisavad õigused selle tegevuse teostamiseks."

#: exceptions.py:93
msgid "Not found."
msgstr "Ei leidnud."

#: exceptions.py:98
msgid "Method \"{method}\" not allowed."
msgstr "Meetod \"{method}\" pole lubatud."

#: exceptions.py:109
msgid "Could not satisfy the request Accept header."
msgstr "Päringu Accept-päist ei suutnud täita."

#: exceptions.py:121
msgid "Unsupported media type \"{media_type}\" in request."
msgstr "Meedia tüüpi {media_type} päringus ei toetata."

#: exceptions.py:134
msgid "Request was throttled."
msgstr "Liiga palju päringuid."

#: fields.py:153 relations.py:132 relations.py:156 validators.py:77
#: validators.py:155
msgid "This field is required."
msgstr "Väli on kohustuslik."

#: fields.py:154
msgid "This field may not be null."
msgstr "Väli ei tohi olla tühi."

#: fields.py:487 fields.py:515
msgid "\"{input}\" is not a valid boolean."
msgstr "\"{input}\" pole kehtiv kahendarv."

#: fields.py:550
msgid "This field may not be blank."
msgstr "See väli ei tohi olla tühi."

#: fields.py:551 fields.py:1324
msgid "Ensure this field has no more than {max_length} characters."
msgstr "Veendu, et see väli poleks pikem kui {max_length} tähemärki."

#: fields.py:552
msgid "Ensure this field has at least {min_length} characters."
msgstr "Veendu, et see väli oleks vähemalt {min_length} tähemärki pikk."

#: fields.py:587
msgid "Enter a valid email address."
msgstr "Sisestage kehtiv e-posti aadress."

#: fields.py:604
msgid "This value does not match the required pattern."
msgstr "Väärtus ei ühti etteantud mustriga."

#: fields.py:615
msgid ""
"Enter a valid \"slug\" consisting of letters, numbers, underscores or "
"hyphens."
msgstr "Sisestage kehtiv \"slug\", mis koosneks tähtedest, numbritest, ala- või sidekriipsudest."

#: fields.py:627
msgid "Enter a valid URL."
msgstr "Sisestage korrektne URL."

#: fields.py:638
msgid "\"{value}\" is not a valid UUID."
msgstr "\"{value}\" pole kehtiv UUID."

#: fields.py:657
msgid "A valid integer is required."
msgstr "Sisendiks peab olema täisarv."

#: fields.py:658 fields.py:692 fields.py:725
msgid "Ensure this value is less than or equal to {max_value}."
msgstr "Veenduge, et väärtus on väiksem kui või võrdne väärtusega {max_value}. "

#: fields.py:659 fields.py:693 fields.py:726
msgid "Ensure this value is greater than or equal to {min_value}."
msgstr "Veenduge, et väärtus on suurem kui või võrdne väärtusega {min_value}."

#: fields.py:660 fields.py:694 fields.py:730
msgid "String value too large."
msgstr "Sõne on liiga pikk."

#: fields.py:691 fields.py:724
msgid "A valid number is required."
msgstr "Sisendiks peab olema arv."

#: fields.py:727
msgid "Ensure that there are no more than {max_digits} digits in total."
msgstr "Veenduge, et kokku pole rohkem kui {max_digits} numbit."

#: fields.py:728
msgid ""
"Ensure that there are no more than {max_decimal_places} decimal places."
msgstr "Veenduge, et komakohti pole rohkem kui {max_decimal_places}. "

#: fields.py:729
msgid ""
"Ensure that there are no more than {max_whole_digits} digits before the "
"decimal point."
msgstr "Veenduge, et täiskohti poleks rohkem kui {max_whole_digits}."

#: fields.py:813
msgid "Datetime has wrong format. Use one of these formats instead: {format}."
msgstr "Valesti formaaditud kuupäev-kellaaeg. Kasutage mõnda neist: {format}."

#: fields.py:814
msgid "Expected a datetime but got a date."
msgstr "Ootasin kuupäev-kellaaeg andmetüüpi, kuid sain hoopis kuupäeva."

#: fields.py:878
msgid "Date has wrong format. Use one of these formats instead: {format}."
msgstr "Valesti formaaditud kuupäev. Kasutage mõnda neist: {format}."

#: fields.py:879
msgid "Expected a date but got a datetime."
msgstr "Ootasin kuupäeva andmetüüpi, kuid sain hoopis kuupäev-kellaaja."

#: fields.py:936
msgid "Time has wrong format. Use one of these formats instead: {format}."
msgstr "Valesti formaaditud kellaaeg. Kasutage mõnda neist: {format}."

#: fields.py:992 fields.py:1036
msgid "\"{input}\" is not a valid choice."
msgstr "\"{input}\" on sobimatu valik."

#: fields.py:1037 fields.py:1151 serializers.py:482
msgid "Expected a list of items but got type \"{input_type}\"."
msgstr "Ootasin kirjete järjendit, kuid sain \"{input_type}\" - tüübi."

#: fields.py:1067
msgid "No file was submitted."
msgstr "Ühtegi faili ei esitatud."

#: fields.py:1068
msgid ""
"The submitted data was not a file. Check the encoding type on the form."
msgstr "Esitatud andmetes ei olnud faili. Kontrollige vormi kodeeringut."

#: fields.py:1069
msgid "No filename could be determined."
msgstr "Ei suutnud tuvastada failinime."

#: fields.py:1070
msgid "The submitted file is empty."
msgstr "Esitatud fail oli tühi."

#: fields.py:1071
msgid ""
"Ensure this filename has at most {max_length} characters (it has {length})."
msgstr "Veenduge, et failinimi oleks maksimaalselt {max_length} tähemärki pikk (praegu on {length})."

#: fields.py:1113
msgid ""
"Upload a valid image. The file you uploaded was either not an image or a "
"corrupted image."
msgstr "Laadige üles kehtiv pildifail. Üles laetud fail ei olnud pilt või oli see katki."

#: fields.py:1188
msgid "Expected a dictionary of items but got type \"{input_type}\"."
msgstr "Ootasin kirjete sõnastikku, kuid sain \"{input_type}\"."

#: pagination.py:221
msgid "Invalid page \"{page_number}\": {message}."
msgstr "Sobimatu lehekülg \"{page_number}\": {message}."

#: pagination.py:442
msgid "Invalid cursor"
msgstr "Sobimatu kursor."

#: relations.py:133
msgid "Invalid pk \"{pk_value}\" - object does not exist."
msgstr "Sobimatu primaarvõti \"{pk_value}\" - objekti pole olemas."

#: relations.py:134
msgid "Incorrect type. Expected pk value, received {data_type}."
msgstr "Sobimatu andmetüüp. Ootasin primaarvõtit, sain {data_type}."

#: relations.py:157
msgid "Invalid hyperlink - No URL match."
msgstr "Sobimatu hüperlink - ei leidnud URLi vastet."

#: relations.py:158
msgid "Invalid hyperlink - Incorrect URL match."
msgstr "Sobimatu hüperlink - vale URLi vaste."

#: relations.py:159
msgid "Invalid hyperlink - Object does not exist."
msgstr "Sobimatu hüperlink - objekti ei eksisteeri."

#: relations.py:160
msgid "Incorrect type. Expected URL string, received {data_type}."
msgstr "Sobimatu andmetüüp. Ootasin URLi sõne, sain {data_type}."

#: relations.py:295
msgid "Object with {slug_name}={value} does not exist."
msgstr "Objekti {slug_name}={value} ei eksisteeri."

#: relations.py:296
msgid "Invalid value."
msgstr "Sobimatu väärtus."

#: serializers.py:299
msgid "Invalid data. Expected a dictionary, but got {datatype}."
msgstr "Sobimatud andmed. Ootasin sõnastikku, kuid sain {datatype}."

#: validators.py:22
msgid "This field must be unique."
msgstr "Selle välja väärtus peab olema unikaalne."

#: validators.py:76
msgid "The fields {field_names} must make a unique set."
msgstr "Veerud {field_names} peavad moodustama unikaalse hulga."

#: validators.py:219
msgid "This field must be unique for the \"{date_field}\" date."
msgstr "Selle välja väärtus peab olema unikaalne veerus \"{date_field}\" märgitud kuupäeval."

#: validators.py:234
msgid "This field must be unique for the \"{date_field}\" month."
msgstr "Selle välja väärtus peab olema unikaalneveerus \"{date_field}\" märgitud kuul."

#: validators.py:247
msgid "This field must be unique for the \"{date_field}\" year."
msgstr "Selle välja väärtus peab olema unikaalneveerus \"{date_field}\" märgitud aastal."

#: versioning.py:39
msgid "Invalid version in \"Accept\" header."
msgstr "Sobimatu versioon \"Accept\" päises."

#: versioning.py:70 versioning.py:112
msgid "Invalid version in URL path."
msgstr "Sobimatu versioon URLi rajas."

#: versioning.py:138
msgid "Invalid version in hostname."
msgstr "Sobimatu versioon hostinimes."

#: versioning.py:160
msgid "Invalid version in query parameter."
msgstr "Sobimatu versioon päringu parameetris."

#: authtoken/serializers.py:20
msgid "User account is disabled."
msgstr "Kasutajakonto on suletud."

#: authtoken/serializers.py:23
msgid "Unable to log in with provided credentials."
msgstr "Sisselogimine antud tunnusega ebaõnnestus."

#: authtoken/serializers.py:26
msgid "Must include \"username\" and \"password\"."
msgstr "Peab sisaldama \"kasutajatunnust\" ja \"slasõna\"."
